### ISSUE TITLE
g-watch-wear crashes every minute on Android 14

### ISSUE THREAD

**Issue by hansj10** [trupici/G-Watch-Wear#21] opened 2023-10-15 12:08 UTC
The g-watch-wear app crashes on my Android 14 Pixel 7 Pro.
libre 3 via juggluco to g-watch-wear app.
open packet console, crash when receiving the packet from juggluco. You do not have to open the packet console, it's just to visually see the crash. Without you see no update on the watch and a android system message that g-watch-app crashes.

The tizen g-watch app works fine with getting data from juggluco.

**Comment by hansj10** [comment] 2023-10-17 11:08
Maybe the crash is not related to juggluco, just changed my sensor to a Dexcom G7, the app closes as well. 
So I removed all data sources, but the app still crashes. 
Seems that g-watch-wear is simply unusable on Android 14

**Comment by suside** [comment] 2023-10-20 05:39
Can confirm on Pixel 7a, all data sources removed, but the app still crashes.

**Comment by suside** [comment] 2023-10-21 06:38
After some debugging I think i found a workaround.
In my case when I disable this option in AAPS 👇 app is working ok with Diabox data source. After disabling it click Reconnect in G-Watch-Wear Packet console.

![image](https://github.com/trupici/G-Watch-Wear/assets/197044/355fc3b8-4dd5-4b39-a8f0-431afe98395b)

**Comment by trupici** [comment] 2023-10-22 12:58
The current version of the app was adopted to Android 13, in that time there was no Android 14 available. The next version will handle this issue

**Comment by trupici** [comment] 2023-10-22 13:07
This is a duplicate of #19

**Comment by hansj10** [comment] 2023-10-22 13:07
AAPS is not an option to disable as I'm just using a sensor (libre3/juggluco) to send the values to the watch. There is no AAPS on my mobile, or I still use a pen instead of an pump..

**Closed as completed by trupici** 2023-10-22 13:07 UTC

**Comment by suside** [comment] 2023-10-23 06:26
@hansj10 That's too bad, in my case it helped :( Perhaps in juggluco there is a similar option that synchronizes data with watches and can be turn off?
